### ISSUE TITLE
Bug at TMainForm.PopupMenu1Popup

### ISSUE THREAD

**Issue by limelect** [delphidabbler/delphi-tips#1]
Mite be nil if nothing yet
add at procedure TMainForm.PopupMenu1Popup(Sender: TObject);
if TV.Selected=nil then exit;

**Comment by delphidabbler** [comment]
Bit baffled: there are no Pascal programs in this repo. 

What program is this please?

**Comment by delphidabbler** [comment]
😄  Worked it out now!: see comment on issue #2

Similar to issue#2.
