### ISSUE TITLE
D10.2.3

### ISSUE THREAD

**Issue by limelect** [delphidabbler/delphi-tips#2]
![Screenshot - 22_06_2020 , 19_33_06](https://user-images.githubusercontent.com/4199131/85312269-4a81df80-b4bf-11ea-84c5-063dca4a6833.jpg)

I compiled with D10.2.3
I loaded Tips.tps
I got on the left pan and the right pan TEXT OK.
I took one tip (press the green icon) got **gibberish** on the right pan

**Comment by delphidabbler** [comment]
Ah ... I get it now!! (see my comment on issue #1).

Is this _Delphi Tips Manager_? If so then, sorry, it's not one of mine and I don't maintain it.

> I did host it on my old website as a favour to the author, but I've never maintained it. What's more it's gone from the new site because it hasn't been updated for years. (Or, if it has, I never got sent any updates!)
